### ISSUE TITLE
Add description attribute in the quote response.

### ISSUE THREAD

**Issue by mohitdd** [samair/Quote-Service#5]

**Comment by samair** [comment]
Proposal: 
New format for quotes endpoint:
`{
  "quotes": {
    "error": false,
    "invalidSymbol": false,
    "quote": {
      "symbol": "VMW",
      "description": "VMware Inc",
      "exch": "N",
      "type": "stock",
      "last": 181.56,
      "change": 2.31,
      "change_percentage": 1.29,
      "volume": 1786305,
      "average_volume": 1518417,
      "last_volume": 243333,
      "trade_date": 1552680335000,
      "open": 179.07,
      "high": 182.48,
      "low": 179.0,
      "close": 181.56,
      "prevclose": 179.26,
      "week_52_high": 183.405,
      "week_52_low": 117.61,
      "bid": 181.01,
      "bidsize": 4,
      "bidexch": "P",
      "bid_date": 1552691885000,
      "ask": 181.99,
      "asksize": 4,
      "askexch": "P",
      "ask_date": 1552691886000,
      "root_symbols": "VMW"
    }
  }
}`

**Comment by samair** [comment]
Fixed with latest commit.
